#! /bin/sh

bspc rule -r "*"

#GAPS and borders
bspc config border_width         2 &
bspc config window_gap           8 &

#BSPWM settings
bspc config split_ratio          3 &
bspc config borderless_monocle   true &
bspc config gapless_monocle      true &
bspc config focus_follows_pointer true &
bspc config focused_border_color "#1F8999"
bspc config presel_feedback_color "#1F8999"

#Autostart
sxhkd &
killall "dunst"
dunst &
killall "compton"
compton --config ~/.config/compton/compton.conf &
setxkbmap es &
killall "nm-applet"
nm-applet &
bash ~/.config/polybar/start.sh &
paplay /usr/share/sounds/freedesktop/stereo/aoe2hd-sound16.wav &
nitrogen --restore &

#Monitors and workspaces
bash ~/.config/bspwm/saneMonitor.sh

#Rules for apps
bspc rule -add firefox desktop=^1 follow=on
bspc rule -add firefox:Toolkit state=floating
bspc rule -add code desktop=^2 follow=on
bspc rule -add Spotify desktop=^9

#workarounds
xsetroot -name "BSPWM" &
wmname LG3D &

